version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ubuntu/new_chatapp
hooks:
   BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

